modLoader="javafxmod"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="dupemod"
version="1.0.0"
displayName="DupeMod"
description="""Клиентский мод для дюпа предметов при нажатии на '='"""
logos="[]"

[[dependencies.dupemod]]
    modId="neoforge"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.dupemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"